name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "v18.14.2"
      - name: Set Git author identity
        run: |
          git remote set-url https://github.com/Joywin2412/Foodie.git
          git config --global user.name "Joywin2412"
          git config --global user.email "2021ugcs104@nitjsr.ac.in"
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run deploy
        env:
          CI: false

      # - name: Run tests
      #   run: npm test
      #   env:
      #     CI: false
